#! /bin/sh

# Installation
# - Move this to /etc/init.d/servidordesensores
# - chmod +x this
#
# Starting and stopping
# - Start: `service servidordesensoresstart` or `/etc/init.d/servidordesensoresstart`
# - Stop: `service servidordesensoresstop` or `/etc/init.d/servidordesensoresstop`



NAME=servidordesensores
DESC="Daemon para recibir tramas de los sensores de VOC"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="/var/log/${NAME}.log"

DAEMON="/opt/lampp/bin/php"
DAEMON_OPTS="/opt/lampp/htdocs/voc-app/servidor_de_sensores.php"

START_OPTS="--start --background --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} ${DAEMON_OPTS}"
STOP_OPTS="--stop --pidfile ${PIDFILE}"

test -x $DAEMON || exit 0

set -e

case "$1" in
    start)
        echo -n "Starting ${DESC}: "
        start-stop-daemon $START_OPTS >> $LOGFILE
        echo "$NAME."
        ;;
    stop)
        echo -n "Stopping $DESC: "
        start-stop-daemon $STOP_OPTS
        echo "$NAME."
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        echo -n "Restarting $DESC: "
        start-stop-daemon $STOP_OPTS
        sleep 1
        start-stop-daemon $START_OPTS >> $LOGFILE
        echo "$NAME."
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0
